name: New Pull Request Alert

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      API_URL: "https://ctf.catch-the-frog.com"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: healthcheck
      continue-on-error: true
      env:
        URL: ${{env.API_URL}}
        USER: ${{ secrets.USER }}
        PW: ${{ secrets.USER_CRED }}
      run: |
        echo $(ls)
        
    - name: send_run_log
      continue-on-error: true
      env:
        URL: ${{env.API_URL}}
        USER: ${{ secrets.USER }}
        PW: ${{ secrets.USER_CRED }}
      run: |
        echo $(ls)
        
    - name: send_slack_alert
      continue-on-error: true
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        echo $(ls)

    - name: backport_assign_check
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        URL: ${{env.API_URL}}
        USER: ${{ secrets.USER }}
        PW: ${{ secrets.USER_CRED }}
      run: |
        echo $(ls)
